# Numpy

## 1. Array 생성

In [1]:
import numpy as np

In [7]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(a)

[1 2 3]


In [8]:
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [5]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

(2, 3)
1 2 4


## 2. Array 생성 함수

In [10]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

[[0. 0.]
 [0. 0.]]


In [11]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

[[1. 1.]]


In [13]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0.04641578 0.11715511]
 [0.64310915 0.20932793]]


## 3. Array 인덱싱

In [14]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
print(row_r1)
print(row_r1.shape)

[5 6 7 8]
(4,)


In [20]:
row_r2 = a[1:2, :]    # Rank 1 view of the second row of a
print(row_r2)
print(row_r2.shape)

[[5 6 7 8]]
(1, 4)


In [21]:
col_r1=a[:,1]
print(col_r1)
print(col_r1.shape)

[ 2  6 10]
(3,)


In [22]:
col_r2=a[:,1:2]
print(col_r2)
print(col_r2.shape)

[[ 2]
 [ 6]
 [10]]
(3, 1)


## 4. Array DataType

In [23]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int64
float64
int64


## 5. Array calculation

In [24]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [25]:
print(x+y)

[[ 6  8]
 [10 12]]


In [26]:
print(x-y)

[[-4 -4]
 [-4 -4]]


In [27]:
print(x*y)

[[ 5 12]
 [21 32]]


In [28]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


## 6. Array calculation (Matrix Multiplication)

In [54]:
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [56]:
v=np.array([9,10])
print(v)

[ 9 10]


### Inner product of vectors

In [71]:
w=np.array([3,4])
print(np.dot(v,w))

67


In [72]:
print(np.dot(w,v))

67


### Matrix/vector product

In [61]:
print(np.dot(v,x))

[49 68 87]


In [62]:
print(np.dot(x,v))

ValueError: shapes (2,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)

### Matrix/Matrix product 

In [63]:
y=np.array([[1,2],[3,4],[5,6]])

In [64]:
print(np.dot(x,y))

[[22 28]
 [49 64]]


## 7. Reshape

In [65]:
print(w)

[3 4]


In [76]:
print(w.shape)

(2,)


In [73]:
np.dot(w,x)

array([19, 26, 33])

In [78]:
w=w.reshape(1,-1)
print(w)

[[3 4]]


In [79]:
print(w.shape)

(1, 2)


In [80]:
print(x)
np.dot(w,x)

[[1 2 3]
 [4 5 6]]


array([[19, 26, 33]])